# Generated by Django 4.2.1 on 2023-08-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=128)),
                ('invoice_date', models.DateField(auto_now=True)),
                ('patient_name', models.CharField(max_length=128)),
                ('patient_surname', models.CharField(blank=True, max_length=128)),
                ('patient_address', models.CharField(blank=True, max_length=512)),
                ('invoice_type', models.CharField(choices=[('G', 'Gotovina'), ('T', 'Transakcijski račun')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=128)),
                ('article_price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('number_of_articles', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='invoicetest.invoice')),
            ],
        ),
    ]
