# Generated by Django 4.2.1 on 2023-06-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iostestapi', '0002_patientimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimages',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='iostestapi.patient'),
        ),
    ]
